services:
  koin-web:
    build:
      context: .
      args:
        EXPO_PUBLIC_SUPABASE_URL: ${EXPO_PUBLIC_SUPABASE_URL}
        EXPO_PUBLIC_SUPABASE_ANON_KEY: ${EXPO_PUBLIC_SUPABASE_ANON_KEY}
    container_name: koin-web
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.koin.rule=Host(`koin.sergiojover.dev`)"
      - "traefik.http.routers.koin.entrypoints=websecure"
      - "traefik.http.routers.koin.tls.certresolver=letsencrypt"
      - "traefik.http.services.koin.loadbalancer.server.port=80"

networks:
  web:
    external: true
